### ISSUE TITLE
Cannot find module 'material-design-lite' on section 3.2

### ISSUE THREAD

**Issue by rezacute** [juristr/learning-angular2-directives-course#1]
I have tried to build section 3.2 but struct on 'material-design-lite'

**Comment by juristr** [comment]
@rezacute Hi, I'm sorry for responding so late. 😢  For some reason I didn't get notified about this new issue here.

I'll immediately check and get back to you soon. Also, I'm in the process of upgrading the entire src code to the latest RC.1 in the coming days.

**Comment by juristr** [comment]
I've just upgraded the [branch 3.2](https://github.com/juristr/learning-angular2-directives-course/tree/3.2-scanning-new-sensors-v2) to the latest Angular RC.1. So far everything seems fine and runs properly.

What you might see is a TypeScript error because there's no typing definition file registered for 'material-design-lite'. But if the application runs, you don't have to worry about that for now. We'll fix that in a later section.

**Comment by juristr** [comment]
Feel free to reopen the issue if the problem persists :smile:

**Comment by rezacute** [comment]
@juristr thanks.
